name: Release rc

on:
  workflow_dispatch:

jobs:
  build-release:
    environment: 'nuget release candidates'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore vstest
      run: dotnet restore --packages ./.vstest/
      working-directory: 'src/Stryker.Core/Stryker.Core/ToolHelpers/'
    - name: Test
      run: dotnet test --verbosity normal
    - name: Pack
      run: dotnet pack src/Stryker.Core/Stryker.Core/Stryker.Core.csproj --output $GITHUB_WORKSPACE/release
    - name: Pack
      run: dotnet pack src/Stryker.CLI/Stryker.CLI/Stryker.CLI.csproj --output $GITHUB_WORKSPACE/release
    - name: Push
      env:
        NUGET_KEY: ${{ secrets.NugetKey }}
      run: dotnet nuget push --output "$GITHUB_WORKSPACE/release/*.nupkg" -k $NUGET_KEY
